-- Table Creation Script for Customer Loyalty Points & Rewards Automation System
-- Drops existing tables, creates new tables with constraints, and inserts sample data

-- Connect as loyalty_owner user
-- CONN loyalty_owner/frank@localhost:1521/tue_26652_frank_loyalty_db

-- Drop existing tables (in reverse order of creation to avoid foreign key constraints)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE REDEMPTIONS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOYALTY_POINTS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PURCHASES CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE REWARDS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

-- Drop sequences if they exist
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE REDEMPTIONS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE LOYALTY_POINTS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PURCHASES_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE REWARDS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CUSTOMERS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

-- Create sequences for primary key generation
CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PURCHASES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LOYALTY_POINTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REWARDS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REDEMPTIONS_SEQ START WITH 1 INCREMENT BY 1;

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
  customer_id NUMBER(10) CONSTRAINT CUSTOMERS_PK PRIMARY KEY,
  full_name VARCHAR2(100) CONSTRAINT CUSTOMERS_NAME_NN NOT NULL,
  phone VARCHAR2(20) CONSTRAINT CUSTOMERS_PHONE_UQ UNIQUE,
  email VARCHAR2(100) CONSTRAINT CUSTOMERS_EMAIL_UQ UNIQUE,
  registration_date DATE DEFAULT SYSDATE
);

-- Create PURCHASES table
CREATE TABLE PURCHASES (
  purchase_id NUMBER(12) CONSTRAINT PURCHASES_PK PRIMARY KEY,
  customer_id NUMBER(10) CONSTRAINT PURCHASES_CUST_ID_NN NOT NULL,
  purchase_date DATE CONSTRAINT PURCHASES_DATE_NN NOT NULL,
  amount NUMBER(10,2) CONSTRAINT PURCHASES_AMOUNT_NN NOT NULL CONSTRAINT PURCHASES_AMOUNT_CHK CHECK (amount > 0),
  store_location VARCHAR2(50) CONSTRAINT PURCHASES_LOCATION_NN NOT NULL,
  CONSTRAINT PURCHASES_CUST_FK FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id)
);

-- Create REWARDS table
CREATE TABLE REWARDS (
  reward_id NUMBER(6) CONSTRAINT REWARDS_PK PRIMARY KEY,
  reward_name VARCHAR2(100) CONSTRAINT REWARDS_NAME_NN NOT NULL,
  points_required NUMBER(8) CONSTRAINT REWARDS_POINTS_NN NOT NULL CONSTRAINT REWARDS_POINTS_CHK CHECK (points_required > 0),
  availability_status VARCHAR2(20) CONSTRAINT REWARDS_STATUS_NN NOT NULL CONSTRAINT REWARDS_STATUS_CHK CHECK (availability_status IN ('AVAILABLE', 'UNAVAILABLE'))
);

-- Create LOYALTY_POINTS table
CREATE TABLE LOYALTY_POINTS (
  point_id NUMBER(15) CONSTRAINT LOYALTY_POINTS_PK PRIMARY KEY,
  customer_id NUMBER(10) CONSTRAINT LOYALTY_POINTS_CUST_ID_NN NOT NULL,
  points NUMBER(8) CONSTRAINT LOYALTY_POINTS_POINTS_NN NOT NULL CONSTRAINT LOYALTY_POINTS_POINTS_CHK CHECK (points >= 0),
  earned_date DATE CONSTRAINT LOYALTY_POINTS_EARNED_NN NOT NULL,
  expiry_date DATE CONSTRAINT LOYALTY_POINTS_EXPIRY_NN NOT NULL,
  status VARCHAR2(20) CONSTRAINT LOYALTY_POINTS_STATUS_NN NOT NULL CONSTRAINT LOYALTY_POINTS_STATUS_CHK CHECK (status IN ('ACTIVE', 'EXPIRED', 'REDEEMED')),
  purchase_id NUMBER(12),
  CONSTRAINT LOYALTY_POINTS_CUST_FK FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),
  CONSTRAINT LOYALTY_POINTS_PURCHASE_FK FOREIGN KEY (purchase_id) REFERENCES PURCHASES(purchase_id)
);

-- Create REDEMPTIONS table
CREATE TABLE REDEMPTIONS (
  redemption_id NUMBER(12) CONSTRAINT REDEMPTIONS_PK PRIMARY KEY,
  customer_id NUMBER(10) CONSTRAINT REDEMPTIONS_CUST_ID_NN NOT NULL,
  reward_id NUMBER(6) CONSTRAINT REDEMPTIONS_REWARD_ID_NN NOT NULL,
  redemption_date DATE CONSTRAINT REDEMPTIONS_DATE_NN NOT NULL,
  points_deducted NUMBER(8) CONSTRAINT REDEMPTIONS_POINTS_NN NOT NULL CONSTRAINT REDEMPTIONS_POINTS_CHK CHECK (points_deducted > 0),
  CONSTRAINT REDEMPTIONS_CUST_FK FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),
  CONSTRAINT REDEMPTIONS_REWARD_FK FOREIGN KEY (reward_id) REFERENCES REWARDS(reward_id)
);

-- Create indexes for performance optimization
CREATE INDEX CUSTOMERS_PHONE_IX ON CUSTOMERS(phone);
CREATE INDEX CUSTOMERS_EMAIL_IX ON CUSTOMERS(email);
CREATE INDEX PURCHASES_CUSTOMER_IX ON PURCHASES(customer_id);
CREATE INDEX LOYALTY_POINTS_CUSTOMER_IX ON LOYALTY_POINTS(customer_id);
CREATE INDEX LOYALTY_POINTS_STATUS_IX ON LOYALTY_POINTS(status);
CREATE INDEX REDEMPTIONS_CUSTOMER_IX ON REDEMPTIONS(customer_id);

-- Display table structures
DESC CUSTOMERS;
DESC PURCHASES;
DESC REWARDS;
DESC LOYALTY_POINTS;
DESC REDEMPTIONS;

-- Display constraints
SELECT table_name, constraint_name, constraint_type FROM user_constraints 
WHERE table_name IN ('CUSTOMERS', 'PURCHASES', 'REWARDS', 'LOYALTY_POINTS', 'REDEMPTIONS')
ORDER BY table_name, constraint_type;